@extends('front.layouts.layout')

@section('header')
@endsection
@section('styles')
    <link rel="stylesheet" href="{{ asset('css/location.css') }}" media="screen" defer>
@endsection
@section('content')
    <main>

        <!-- HERO -->
        <section class="hero" style="background:rgba(54, 54, 54, .5) url('/assets/front/images/hero-image.webp') no-repeat center center / cover;">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-8">
                        <h1>Terms and Conditions</h1>
                    </div>
                </div>
            </div>
        </section>

        <!-- ARTICLE -->
        <section class="article">
            <div class="container">
                <div class="row article-item">
                    <div class="col-12">
                        <h6>The effective date of this Agreement is May 8, 2021.</h6>
                        <p>By accessing or using any features of the site, including the purchase of products and services on the site located at <a href="#">www.appliancerepairmen.net</a> (the “Site“) and operated and managed 24h Local Services (“we” or “us”), you agree to be bound by these terms and conditions (collectively, “Terms“). All visitors to and users of any aspects of this Site (collectively, “Users”) are bound by these Terms. We reserve the right to modify the Terms at any time without prior notice to you. Therefore, we recommend that you read these terms and conditions carefully each time you use this Web site.</p>
                        <p>Please note that the guidelines, policies and other terms and conditions of use of other Web sites affiliated with this Site may vary from these Terms.</p>
                        <p>As a User of this Site you may, from time to time, post content and share it with other users, read content generated by other visitors to this Site and other affiliated sites, and view third party postings and reviews regarding products and services. If you wish to post content to, or participate in this Site Other than simply by reading product information and content and reviews posted by others, you must register using the registration form.</p>
                        <p>These Terms set out the legally binding terms with respect to your use of this Site. Please read these Terms carefully. Your access to and use of this Site constitutes your acceptance of all the provisions of these Terms. If you are unwilling to be bound by these Terms, you should not access or use this Site.</p><br/>
                        <h5>Eligibility</h5>
                        <p>This Site is not targeted towards, nor intended for use by anyone under the age of 18. By using this Site, you represent and warrant that you are 18 years of age or older.</p><br/>
                        <h5>Changes to the Appliance Repairmen Site</h5>
                        <p>You agree and understand that this Site, including any and all the features available via this Site and any User Content (as defined below), may be modified by us, in our sole discretion, at any time without prior notice. Unless expressly stated otherwise, any new features, new services, enhancements or modifications to this Site implemented after your initial access to this Site shall be subject to these Terms.</p><br/>
                        <h5>Use of the Site/Services</h5>
                        <p>You may use this Site for your personal or commercial use.</p><br/>
                        <h5>Restrictions on Rights to Use</h5>
                        <p>Without limiting the generality of any other provisions of these Terms, you agree that you shall not (and you agree not to allow any other individual or entity to):</p>
                        <ul>
                            <li>reformat or frame any portion of any Web pages that are part of this Site;</li>
                            <li>submit to Site any content that is unlawful or facilitates, constitutes, promotes or encourages illegal activity; or otherwise use this Site to transfer or store illegal material, including any material deemed threatening or obscene;</li>
                            <li>copy or store any User Content offered on this Site other than for your personal, non-commercial use;</li>
                            <li>take any action that imposes, or may impose, in our sole discretion, an unreasonable or disproportionately large load on this Site or the IT infrastructure used to operate and make this Site Available.</li>
                        </ul><br/>
                        <h5>Privacy</h5>
                        <p>Use of this Site is also governed by our <a href="#">Privacy Policy</a> which we encourage you to review.</p><br/>
                        <h5>Third Party Advertisements and Links to Third Party Sites</h5>
                        <p>We may display on this Site advertisements from third parties, such as banner advertisements and pop-up texts, and links to third party sites. We are not responsible for the content of such advertisements or links, any products, services or other materials relating to such advertisements, any linked site, or any link contained in a linked site. The display of any advertisement or link does not imply endorsement by us of the advertisement or linked site or any content therein. Advertisers may gather and use information about Users.</p><br/>
                        <h5>Changes to Terms and Conditions</h5>
                        <p>We reserve the right to make changes at any time to these Terms. Any modifications to the Terms will be effective upon posting. You agree to review the Terms periodically so that you are aware of any modifications. Your continued use of this Site after any modifications indicates your acceptance of the modified Terms.</p><br/>
                        <h5>Applicable law</h5>
                        <p>By visiting this Site, you agree that the laws of the State of Delaware, without regard to principles of conflict of laws, will govern these Terms and any dispute of any sort that might arise between you and this Site.</p><br/>
                        <h5>Miscellaneous</h5>
                        <p>We may provide you with notices, including those regarding changes to these Terms, by email, regular mail, or postings on this Site. These Terms, which shall be deemed accepted by you upon your use of this Site, constitute the entire agreement among you and us regarding use of this Site. The headings in these Terms are for convenience only and have no legal or contractual effect. These Terms incorporate the Privacy Policy for the this Site and any notices regarding this Site.</p><br/>
                        <h5>Contact and Violations</h5>
                        <p>Please contact us with any questions regarding these Terms. Please report any violations of the Terms to <a href="mailto:info@appliancerepairmen.net.">info@appliancerepairmen.net</a>.</p>
                    </div>
                </div>
            </div>
        </section>
    </main>
@endsection



@section('footer')
@endsection
